-- Oracle SQL*Plus script: export current schema DDL to schema.sql
-- Usage example:
--   sqlplus user/password@host:1521/service @inspectdb.sql tests/_data/mock/database/schema.sql

SET PAGESIZE 0
SET LONG 1000000
SET LONGCHUNKSIZE 1000000
SET LINESIZE 32767
SET TRIMSPOOL ON
SET HEADING OFF
SET FEEDBACK OFF
SET VERIFY OFF

BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'TABLESPACE', FALSE);
END;
/

SPOOL &1

SELECT DBMS_METADATA.GET_DDL('TABLE', table_name, USER)
FROM user_tables
ORDER BY table_name;

SELECT DBMS_METADATA.GET_DDL('SEQUENCE', sequence_name, USER)
FROM user_sequences
ORDER BY sequence_name;

SPOOL OFF

