<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev)
namespace app\models;

/**
 * Администратор – наследник User, использует ту же таблицу,
 * но с дискриминатором type='admin'. В Yii2 это может быть реализовано через
 * переопределение tableName и условий.
 */
class Admin extends User
{
    public static function tableName()
    {
        return 'user';
        // та же таблица
    }
    public static function find()
    {
        // добавляем условие по умолчанию для администраторов
        return parent::find()->where(['type' => 'admin']);
    }
    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $this->type = 'admin';
            return true;
        }
        return false;
    }
    /**
     * @generated by doctrinify
     */
    protected $id;
    /**
     * @generated by doctrinify
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @generated by doctrinify
     */
    public function setId($value): self
    {
        $this->id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $username;
    /**
     * @generated by doctrinify
     */
    public function getUsername()
    {
        return $this->username;
    }
    /**
     * @generated by doctrinify
     */
    public function setUsername($value): self
    {
        $this->username = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $password_hash;
    /**
     * @generated by doctrinify
     */
    public function getPasswordHash()
    {
        return $this->password_hash;
    }
    /**
     * @generated by doctrinify
     */
    public function setPasswordHash($value): self
    {
        $this->password_hash = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $type;
    /**
     * @generated by doctrinify
     */
    public function getType()
    {
        return $this->type;
    }
    /**
     * @generated by doctrinify
     */
    public function setType($value): self
    {
        $this->type = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $created_at;
    /**
     * @generated by doctrinify
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }
    /**
     * @generated by doctrinify
     */
    public function setCreatedAt($value): self
    {
        $this->created_at = $value;
        return $this;
    }
}
