<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev) | diagnostic[warning] local field `product_id` missing in `category` for relation `products`
namespace app\models;

/**
 * Категория с иерархией (parent/children)
 */
class Category extends BaseModel
{
    public static function tableName()
    {
        return 'category';
    }
    public function rules()
    {
        return [[['name'], 'required'], ['parent_id', 'integer'], ['name', 'string', 'max' => 255]];
    }
    public function attributeLabels()
    {
        return ['id' => 'Category ID', 'parent_id' => 'Parent Category', 'name' => 'Category Name'];
    }
    public function getParent()
    {
        return $this->hasOne(self::class, ['id' => 'parent_id']);
    }
    public function getChildren()
    {
        return $this->hasMany(self::class, ['parent_id' => 'id']);
    }
    public function getProductCategories()
    {
        return $this->hasMany(ProductCategory::class, ['category_id' => 'id']);
    }
    public function getProducts()
    {
        return $this->hasMany(Product::class, ['id' => 'product_id'])->via('productCategories');
    }
    /**
     * @generated by doctrinify
     */
    protected $id;
    /**
     * @generated by doctrinify
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @generated by doctrinify
     */
    public function setId($value): self
    {
        $this->id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $parent_id;
    /**
     * @generated by doctrinify
     */
    public function getParentId()
    {
        return $this->parent_id;
    }
    /**
     * @generated by doctrinify
     */
    public function setParentId($value): self
    {
        $this->parent_id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $name;
    /**
     * @generated by doctrinify
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * @generated by doctrinify
     */
    public function setName($value): self
    {
        $this->name = $value;
        return $this;
    }
}
