<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev)
namespace app\models;

/**
 * Модель клиента (простая, одна таблица)
 */
class Customer extends BaseModel
{
    public static function tableName()
    {
        return 'customer';
    }
    public function rules()
    {
        return [[['name', 'email'], 'required'], ['email', 'email'], [['name'], 'string', 'max' => 255], [['email'], 'string', 'max' => 255], [['email'], 'unique']];
    }
    public function attributeLabels()
    {
        return ['id' => 'ID', 'name' => 'Full Name', 'email' => 'Email Address', 'created_at' => 'Registered At'];
    }
    public function getOrders()
    {
        // hasMany через внешний ключ customer_id в таблице order
        return $this->hasMany(Order::class, ['customer_id' => 'id']);
    }
    /**
     * @generated by doctrinify
     */
    protected $id;
    /**
     * @generated by doctrinify
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @generated by doctrinify
     */
    public function setId($value): self
    {
        $this->id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $name;
    /**
     * @generated by doctrinify
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * @generated by doctrinify
     */
    public function setName($value): self
    {
        $this->name = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $email;
    /**
     * @generated by doctrinify
     */
    public function getEmail()
    {
        return $this->email;
    }
    /**
     * @generated by doctrinify
     */
    public function setEmail($value): self
    {
        $this->email = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $created_at;
    /**
     * @generated by doctrinify
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }
    /**
     * @generated by doctrinify
     */
    public function setCreatedAt($value): self
    {
        $this->created_at = $value;
        return $this;
    }
}
