<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev)
namespace app\models;

/**
 * Позиция заказа
 */
class OrderItem extends BaseModel
{
    public static function tableName()
    {
        return 'order_item';
    }
    public function rules()
    {
        return [[['order_id', 'customer_id', 'product_id', 'quantity', 'price'], 'required'], [['order_id', 'customer_id', 'product_id', 'quantity'], 'integer'], ['price', 'number'], ['quantity', 'integer', 'min' => 1]];
    }
    public function attributeLabels()
    {
        return ['id' => 'Item ID', 'order_id' => 'Order', 'customer_id' => 'Customer', 'product_id' => 'Product', 'quantity' => 'Qty', 'price' => 'Price'];
    }
    public function getOrder()
    {
        return $this->hasOne(Order::class, ['order_id' => 'order_id', 'customer_id' => 'customer_id']);
    }
    public function getProduct()
    {
        return $this->hasOne(Product::class, ['id' => 'product_id']);
    }
    /**
     * @generated by doctrinify
     */
    protected $id;
    /**
     * @generated by doctrinify
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @generated by doctrinify
     */
    public function setId($value): self
    {
        $this->id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $order_id;
    /**
     * @generated by doctrinify
     */
    public function getOrderId()
    {
        return $this->order_id;
    }
    /**
     * @generated by doctrinify
     */
    public function setOrderId($value): self
    {
        $this->order_id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $customer_id;
    /**
     * @generated by doctrinify
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }
    /**
     * @generated by doctrinify
     */
    public function setCustomerId($value): self
    {
        $this->customer_id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $product_id;
    /**
     * @generated by doctrinify
     */
    public function getProductId()
    {
        return $this->product_id;
    }
    /**
     * @generated by doctrinify
     */
    public function setProductId($value): self
    {
        $this->product_id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $quantity;
    /**
     * @generated by doctrinify
     */
    public function getQuantity()
    {
        return $this->quantity;
    }
    /**
     * @generated by doctrinify
     */
    public function setQuantity($value): self
    {
        $this->quantity = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $price;
    /**
     * @generated by doctrinify
     */
    public function getPrice()
    {
        return $this->price;
    }
    /**
     * @generated by doctrinify
     */
    public function setPrice($value): self
    {
        $this->price = $value;
        return $this;
    }
}
