<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev) | diagnostic[warning] relation `itemsWithCondition` rejected: contains SQL query modifiers: addOrderBy, onCondition, condition
namespace app\models;

/**
 * Модель заказа с композитным первичным ключом (order_id, customer_id)
 */
class Order extends BaseModel
{
    public static function tableName()
    {
        return 'order';
    }
    public function rules()
    {
        return [[['order_id', 'customer_id', 'order_date'], 'required'], [['order_id', 'customer_id'], 'integer'], ['order_date', 'date', 'format' => 'php:Y-m-d'], ['status', 'string', 'max' => 20], [['order_id', 'customer_id'], 'unique', 'targetAttribute' => ['order_id', 'customer_id']]];
    }
    public function attributeLabels()
    {
        return ['order_id' => 'Order #', 'customer_id' => 'Customer', 'order_date' => 'Date', 'status' => 'Status'];
    }
    public function getCustomer()
    {
        // belongsTo
        return $this->hasOne(Customer::class, ['id' => 'customer_id']);
    }
    public function getItems()
    {
        // hasMany
        return $this->hasMany(OrderItem::class, ['order_id' => 'order_id']);
    }
    public function getItemsWithCondition()
    {
        return $this->hasMany(OrderItem::class, ['order_id' => 'order_id'])->onCondition(['condition' => 'order_item.price > 0'])->addOrderBy(['order_id' => SORT_DESC]);
    }
    /**
     * @generated by doctrinify
     */
    protected $order_id;
    /**
     * @generated by doctrinify
     */
    public function getOrderId()
    {
        return $this->order_id;
    }
    /**
     * @generated by doctrinify
     */
    public function setOrderId($value): self
    {
        $this->order_id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $customer_id;
    /**
     * @generated by doctrinify
     */
    public function getCustomerId()
    {
        return $this->customer_id;
    }
    /**
     * @generated by doctrinify
     */
    public function setCustomerId($value): self
    {
        $this->customer_id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $order_date;
    /**
     * @generated by doctrinify
     */
    public function getOrderDate()
    {
        return $this->order_date;
    }
    /**
     * @generated by doctrinify
     */
    public function setOrderDate($value): self
    {
        $this->order_date = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $status;
    /**
     * @generated by doctrinify
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * @generated by doctrinify
     */
    public function setStatus($value): self
    {
        $this->status = $value;
        return $this;
    }
}
