<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev)
namespace app\models;

/**
 * Промежуточная модель many-to-many product<->category
 */
class ProductCategory extends BaseModel
{
    /** @generated by doctrinify */
    protected $productId;
    /** @generated by doctrinify */
    public function getProductId()
    {
        return $this->productId;
    }
    /** @generated by doctrinify */
    public function setProductId($value): self
    {
        $this->productId = $value;
        return $this;
    }
    /** @generated by doctrinify */
    protected $categoryId;
    /** @generated by doctrinify */
    public function getCategoryId()
    {
        return $this->categoryId;
    }
    /** @generated by doctrinify */
    public function setCategoryId($value): self
    {
        $this->categoryId = $value;
        return $this;
    }
    /** @generated by doctrinify */
    protected $assignedAt;
    /** @generated by doctrinify */
    public function getAssignedAt()
    {
        return $this->assignedAt;
    }
    /** @generated by doctrinify */
    public function setAssignedAt($value): self
    {
        $this->assignedAt = $value;
        return $this;
    }
    public static function tableName()
    {
        return 'product_category';
    }
    public static function primaryKey()
    {
        return ['product_id', 'category_id'];
    }
    public function rules()
    {
        return [[['product_id', 'category_id'], 'required'], [['product_id', 'category_id'], 'integer'], [['product_id', 'category_id'], 'unique', 'targetAttribute' => ['product_id', 'category_id']]];
    }
    public function attributeLabels()
    {
        return ['product_id' => 'Product', 'category_id' => 'Category', 'assigned_at' => 'Assigned At'];
    }
    public function getProduct()
    {
        return $this->hasOne(Product::class, ['id' => 'product_id']);
    }
    public function getCategory()
    {
        return $this->hasOne(Category::class, ['id' => 'category_id']);
    }
}
