<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev) | diagnostic[warning] relation `categoriesWithSql` has SQL modifiers: contains SQL query modifiers: andWhere, joinType, joinWith, addOrderBy, order, orderBy, condition, where | diagnostic[warning] local field `category_id` missing in `PRODUCT` for relation `categories` | diagnostic[warning] local field `category_id` missing in `PRODUCT` for relation `categoriesWithSql`
namespace app\models;

/**
 * Товар
 */
class Product extends BaseModel
{
    /** @generated by doctrinify */
    protected $id;
    /** @generated by doctrinify */
    public function getId()
    {
        return $this->id;
    }
    /** @generated by doctrinify */
    public function setId($value): self
    {
        $this->id = $value;
        return $this;
    }
    /** @generated by doctrinify */
    protected $sku;
    /** @generated by doctrinify */
    public function getSku()
    {
        return $this->sku;
    }
    /** @generated by doctrinify */
    public function setSku($value): self
    {
        $this->sku = $value;
        return $this;
    }
    /** @generated by doctrinify */
    protected $name;
    /** @generated by doctrinify */
    public function getName()
    {
        return $this->name;
    }
    /** @generated by doctrinify */
    public function setName($value): self
    {
        $this->name = $value;
        return $this;
    }
    /** @generated by doctrinify */
    protected $price;
    /** @generated by doctrinify */
    public function getPrice()
    {
        return $this->price;
    }
    /** @generated by doctrinify */
    public function setPrice($value): self
    {
        $this->price = $value;
        return $this;
    }
    /** @generated by doctrinify */
    protected $stock;
    /** @generated by doctrinify */
    public function getStock()
    {
        return $this->stock;
    }
    /** @generated by doctrinify */
    public function setStock($value): self
    {
        $this->stock = $value;
        return $this;
    }
    public static function tableName()
    {
        return 'product';
    }
    public function rules()
    {
        return [[['sku', 'name', 'price'], 'required'], ['sku', 'string', 'max' => 50], ['name', 'string', 'max' => 255], ['price', 'number'], ['stock', 'integer'], ['sku', 'unique']];
    }
    public function attributeLabels()
    {
        return ['id' => 'Product ID', 'sku' => 'SKU', 'name' => 'Product Name', 'price' => 'Price', 'stock' => 'Stock'];
    }
    public function getOrderItems()
    {
        return $this->hasMany(OrderItem::class, ['product_id' => 'id']);
    }
    public function getProductCategories()
    {
        return $this->hasMany(ProductCategory::class, ['product_id' => 'id']);
    }
    public function getCategories()
    {
        return $this->hasMany(Category::class, ['id' => 'category_id'])->via('productCategories');
    }
    public function getCategoriesWithSql()
    {
        return $this->hasMany(Category::class, ['id' => 'category_id'])->via('productCategories')->where(['status' => 'active'])->andWhere(['condition' => 'pc.deleted_at IS NULL'])->orderBy(['name' => SORT_ASC])->addOrderBy(['order' => 'pc.priority DESC'])->joinWith(['productCategories pc'], true, 'LEFT JOIN')->andWhere(['joinType' => 'LEFT JOIN']);
    }
}
