<?php

// @generated by doctrinify (command=tools:orm:generate, version=dev)
namespace app\models;

/**
 * Базовый пользователь (одна таблица с дискриминатором type)
 */
class User extends BaseModel
{
    public static function tableName()
    {
        return 'user';
    }
    public function rules()
    {
        return [[['username', 'password_hash', 'type'], 'required'], ['username', 'string', 'max' => 50], ['password_hash', 'string', 'max' => 255], ['type', 'string', 'max' => 20], ['username', 'unique']];
    }
    public function attributeLabels()
    {
        return ['id' => 'ID', 'username' => 'Username', 'password_hash' => 'Password', 'type' => 'User Type', 'created_at' => 'Created'];
    }
    /**
     * @generated by doctrinify
     */
    protected $id;
    /**
     * @generated by doctrinify
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @generated by doctrinify
     */
    public function setId($value): self
    {
        $this->id = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $username;
    /**
     * @generated by doctrinify
     */
    public function getUsername()
    {
        return $this->username;
    }
    /**
     * @generated by doctrinify
     */
    public function setUsername($value): self
    {
        $this->username = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $password_hash;
    /**
     * @generated by doctrinify
     */
    public function getPasswordHash()
    {
        return $this->password_hash;
    }
    /**
     * @generated by doctrinify
     */
    public function setPasswordHash($value): self
    {
        $this->password_hash = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $type;
    /**
     * @generated by doctrinify
     */
    public function getType()
    {
        return $this->type;
    }
    /**
     * @generated by doctrinify
     */
    public function setType($value): self
    {
        $this->type = $value;
        return $this;
    }
    /**
     * @generated by doctrinify
     */
    protected $created_at;
    /**
     * @generated by doctrinify
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }
    /**
     * @generated by doctrinify
     */
    public function setCreatedAt($value): self
    {
        $this->created_at = $value;
        return $this;
    }
}
