<?php

declare(strict_types=1);

namespace App\Tools\Codegen;

use App\Tools\AST\AstFacade;
use App\Tools\Naming\ColumnNameMapper;
use App\Tools\Schemas\DBIntrospection\TableIntrospectionDto;
use App\Tools\Schemas\Pipeline\Diagnostic;
use App\Tools\Schemas\Pipeline\PhpPersistInstructionSchema;
use App\Tools\Schemas\ToolingProfileInterface;

final class PhpAccessorCodeGenerator
{
    public function __construct(
        private readonly ?AstFacade $astFacade = null,
        private readonly ?ColumnNameMapper $columnNameMapper = null,
    )
    {
    }

    /**
     * @param array<Diagnostic> $diagnostics
     */
    public function buildAstInstruction(
        string                  $className,
        string                  $targetPath,
        TableIntrospectionDto   $table,
        ToolingProfileInterface $profile,
        array                   $diagnostics,
    ): PhpPersistInstructionSchema {
        $nameMapper = $this->columnNameMapper ?? new ColumnNameMapper();
        $fieldNames = [];
        foreach ($table->fields as $field) {
            $fieldName = $nameMapper->toFieldName($field->name);
            if ($fieldName === '' || in_array($fieldName, $fieldNames, true)) {
                continue;
            }
            $fieldNames[] = $fieldName;
        }

        $generatedMarker = sprintf('@generated by %s', $profile->getGenerationNaming());
        $nodes = ($this->astFacade ?? new AstFacade())->buildGeneratedMemberNodes($fieldNames, $generatedMarker);

        $headers = [];
        if ($profile->shouldAddGeneratedMarker()) {
            $headers[] = sprintf('%s (command=tools:orm:generate, version=dev)', $generatedMarker);
        }

        if ($profile->shouldEmbedDiagnostics() && $diagnostics !== []) {
            foreach ($diagnostics as $diagnostic) {
                $headers[] = sprintf('diagnostic[%s] %s', $diagnostic->severity, $diagnostic->message);
            }
        }

        return new PhpPersistInstructionSchema(
            targetPath: $targetPath,
            className: $className,
            astNodes: $nodes,
            headerComments: $headers,
        );
    }
}
