<?php

declare(strict_types=1);

namespace Doctrinify\Tools\Codegen;

use Doctrinify\Tools\Schemas\Pipeline\Diagnostic;
use Doctrinify\Tools\Schemas\DBIntrospection\TableIntrospectionDto;
use Doctrinify\Tools\Schemas\ProjectProfileInterface;

final class PhpAccessorCodeGenerator
{
    /**
     * @param list<Diagnostic> $diagnostics
     */
    public function generate(string $className, TableIntrospectionDto $table, ProjectProfileInterface $profile, array $diagnostics): string
    {
        $short = $this->shortClassName($className);
        $lines = [];
        $lines[] = '<?php';
        $lines[] = '';
        $lines[] = 'declare(strict_types=1);';
        $lines[] = '';

        if ($profile->shouldAddGeneratedMarker()) {
            $lines[] = sprintf('// @generated by doctrinify (strategy=%s, command=tools:orm:generate, version=dev)', $profile->getRegenerationStrategy());
            $lines[] = '';
        }

        if ($profile->shouldEmbedDiagnostics() && $diagnostics !== []) {
            foreach ($diagnostics as $diagnostic) {
                $lines[] = sprintf('// diagnostic[%s]: %s', $diagnostic->severity, $diagnostic->message);
            }
            $lines[] = '';
        }

        $lines[] = sprintf('namespace %s;', $profile->getGeneratedPhpNamespace());
        $lines[] = '';
        $lines[] = sprintf('class %s', $short);
        $lines[] = '{';

        $fields = array_values($table->fields);
        foreach ($fields as $field) {
            $lines[] = sprintf('    protected $%s = null;', $field->name);
        }

        if ($fields !== []) {
            $lines[] = '';
        }

        foreach ($fields as $index => $field) {
            $methodSuffix = str_replace(' ', '', ucwords(str_replace('_', ' ', $field->name)));
            $lines[] = sprintf('    public function get%s()', $methodSuffix);
            $lines[] = '    {';
            $lines[] = sprintf('        return $this->%s;', $field->name);
            $lines[] = '    }';
            $lines[] = '';
            $lines[] = sprintf('    public function set%s($value): self', $methodSuffix);
            $lines[] = '    {';
            $lines[] = sprintf('        $this->%s = $value;', $field->name);
            $lines[] = '';
            $lines[] = '        return $this;';
            $lines[] = '    }';

            if ($index !== count($fields) - 1) {
                $lines[] = '';
            }
        }

        $lines[] = '}';

        return implode("\n", $lines) . "\n";
    }

    public function buildFilename(string $className): string
    {
        return $this->shortClassName($className) . '.php';
    }

    private function shortClassName(string $fqn): string
    {
        $parts = explode('\\', $fqn);
        return end($parts) ?: $fqn;
    }
}
