<?php

declare(strict_types=1);

namespace Doctrinify\Tools\Codegen;

use Doctrinify\Tools\AST\AstFacade;
use Doctrinify\Tools\Schemas\DBIntrospection\TableIntrospectionDto;
use Doctrinify\Tools\Schemas\Pipeline\Diagnostic;
use Doctrinify\Tools\Schemas\Pipeline\PhpPersistInstructionSchema;
use Doctrinify\Tools\Schemas\ProjectProfileInterface;

final class PhpAccessorCodeGenerator
{
    private const GENERATED_MARKER = '@generated by doctrinify';

    public function __construct(private readonly ?AstFacade $astFacade = null)
    {
    }

    /**
     * @param list<Diagnostic> $diagnostics
     */
    public function buildAstInstruction(
        string $className,
        string $targetPath,
        TableIntrospectionDto $table,
        ProjectProfileInterface $profile,
        array $diagnostics,
    ): PhpPersistInstructionSchema {
        $fieldNames = [];
        foreach ($table->fields as $field) {
            $fieldNames[] = $field->name;
        }

        $nodes = ($this->astFacade ?? new AstFacade())->buildGeneratedMemberNodes($fieldNames);

        $headers = [];
        if ($profile->shouldAddGeneratedMarker()) {
            $headers[] = sprintf(
                '%s (strategy=%s, command=tools:orm:generate, version=dev)',
                self::GENERATED_MARKER,
                $profile->getRegenerationStrategy()
            );
        }

        if ($profile->shouldEmbedDiagnostics() && $diagnostics !== []) {
            foreach ($diagnostics as $diagnostic) {
                $headers[] = sprintf('diagnostic[%s] %s', $diagnostic->severity, $diagnostic->message);
            }
        }

        return new PhpPersistInstructionSchema(
            mode: 'ast_nodes',
            targetPath: $targetPath,
            className: $className,
            content: null,
            astNodes: $nodes,
            headerComments: $headers,
        );
    }
}
