<?php

declare(strict_types=1);

namespace App\Tools\AST;

use App\Tools\Schemas\Pipeline\ModelIntrospectionSchema;
use App\Tools\Schemas\Pipeline\ModelRelationSchema;
use PhpParser\Comment;
use PhpParser\Comment\Doc;
use PhpParser\Node;
use PhpParser\Node\Expr;
use PhpParser\Node\Name;
use PhpParser\Node\Param;
use PhpParser\Node\Stmt;
use PhpParser\ParserFactory;
use PhpParser\PrettyPrinter\Standard;

final class AstFacade
{
    private const GENERATED_MARKER_PREFIX = '@generated by ';

    /**
     * @return array{fqn:string,extends:?string,methodNames:list<string>,isAbstract:bool}|null
     */
    public function extractFirstClassInfo(string $filePath): ?array
    {
        $ast = $this->parsePhpFile($filePath);
        $context = $this->findFirstClassWithNamespace($ast);
        if ($context === null) {
            return null;
        }

        $class = $context['class'];
        $namespace = $context['namespace'];
        $shortName = $class->name?->toString() ?? '';
        if ($shortName === '') {
            return null;
        }

        $fqn = $namespace !== '' ? $namespace . '\\' . $shortName : $shortName;
        $extends = null;
        if ($class->extends instanceof Node\Name) {
            $extends = $class->extends->toString();
            if (!str_contains($extends, '\\') && $namespace !== '') {
                $extends = $namespace . '\\' . $extends;
            }
        }

        $methodNames = [];
        foreach ($class->getMethods() as $method) {
            $methodNames[] = $method->name->toString();
        }

        return [
            'fqn' => $fqn,
            'extends' => $extends,
            'methodNames' => $methodNames,
            'isAbstract' => $class->isAbstract(),
        ];
    }

    /**
     * @return array<int, Stmt>
     */
    public function parsePhpFile(string $filePath): array
    {
        if (!class_exists(ParserFactory::class)) {
            throw new \RuntimeException('nikic/php-parser is required');
        }

        $code = file_get_contents($filePath);
        if ($code === false) {
            throw new \RuntimeException(sprintf('Failed to read PHP file: %s', $filePath));
        }

        $factory = new ParserFactory();
        $parser = method_exists($factory, 'createForNewestSupportedVersion')
            ? $factory->createForNewestSupportedVersion()
            : $factory->createForHostVersion();
        $ast = $parser->parse($code);
        if (!is_array($ast)) {
            throw new \RuntimeException(sprintf('Failed to parse PHP AST: %s', $filePath));
        }

        return $ast;
    }

    /**
     * @param array<int, Stmt> $ast
     * @return array{class:Stmt\Class_,namespace:string}|null
     */
    private function findFirstClassWithNamespace(array $ast): ?array
    {
        foreach ($ast as $stmt) {
            if ($stmt instanceof Stmt\Namespace_) {
                $namespace = $stmt->name?->toString() ?? '';
                foreach ($stmt->stmts as $nsStmt) {
                    if ($nsStmt instanceof Stmt\Class_) {
                        return ['class' => $nsStmt, 'namespace' => $namespace];
                    }
                }
                continue;
            }

            if ($stmt instanceof Stmt\Class_) {
                return ['class' => $stmt, 'namespace' => ''];
            }
        }

        return null;
    }

    /**
     * @param array<string> $methodNames
     */
    public function hasModelHeuristics(array $methodNames): bool
    {
        $lookup = array_fill_keys($methodNames, true);
        return isset($lookup['tableName']) || isset($lookup['relations']) || isset($lookup['rules']) || isset($lookup['primaryKey']);
    }

    /**
     * @param array<string> $relationSqlModifiers
     */
    public function introspectModel(string $className, string $filePath, array $relationSqlModifiers): ?ModelIntrospectionSchema
    {
        if (!is_file($filePath)) {
            return null;
        }

        try {
            $ast = $this->parsePhpFile($filePath);
            $classNode = $this->findClassByShortName($ast, $this->shortClassName($className));
        } catch (\Throwable) {
            return null;
        }

        if (!$classNode instanceof Stmt\Class_) {
            return null;
        }

        $extends = null;
        if ($classNode->extends instanceof Node\Name) {
            $extends = $classNode->extends->toString();
            if (!str_contains($extends, '\\')) {
                $namespace = substr($className, 0, (int)strrpos($className, '\\'));
                $extends = $namespace . '\\' . $extends;
            }
        }

        $table = null;
        $relations = [];
        $discriminator = null;
        $rules = [];
        $labels = [];
        $primaryKey = [];

        foreach ($classNode->getMethods() as $method) {
            $name = $method->name->toString();
            if ($name === 'tableName') {
                $table = $this->extractReturnedString($method) ?? $table;
                continue;
            }
            if ($name === 'primaryKey') {
                $primaryKey = $this->extractReturnedStringArray($method);
                continue;
            }
            if ($name === 'rules') {
                $rules = $this->extractRulesFromMethod($method);
                continue;
            }
            if ($name === 'attributeLabels') {
                $labels = $this->extractAssocStringMapFromMethod($method);
                continue;
            }
            if ($name === 'find') {
                $discriminator = $this->extractTypeDiscriminatorFromFind($method) ?? $discriminator;
                continue;
            }
            if ($name === 'beforeSave') {
                $discriminator = $this->extractTypeDiscriminatorFromBeforeSave($method) ?? $discriminator;
                continue;
            }
            if (!str_starts_with($name, 'get')) {
                continue;
            }

            $relation = $this->extractRelationFromMethod($className, $method, $relationSqlModifiers);
            if ($relation !== null) {
                $relations[] = $relation;
            }
        }

        return new ModelIntrospectionSchema(
            className: $className,
            extends: $extends,
            isAbstract: $classNode->isAbstract(),
            table: $table,
            relations: $relations,
            discriminator: $discriminator,
            rules: $rules,
            attributeLabels: $labels,
            primaryKey: $primaryKey,
        );
    }

    /**
     * @param array<int, Stmt> $ast
     */
    public function findClassByShortName(array $ast, string $shortClassName): ?Stmt\Class_
    {
        foreach ($ast as $stmt) {
            if ($stmt instanceof Stmt\Namespace_) {
                foreach ($stmt->stmts as $nsStmt) {
                    if ($nsStmt instanceof Stmt\Class_ && $nsStmt->name?->toString() === $shortClassName) {
                        return $nsStmt;
                    }
                }
                continue;
            }

            if ($stmt instanceof Stmt\Class_ && $stmt->name?->toString() === $shortClassName) {
                return $stmt;
            }
        }

        return null;
    }

    private function shortClassName(string $fqn): string
    {
        $parts = explode('\\', $fqn);
        return end($parts) ?: $fqn;
    }

    private function extractReturnedString(Stmt\ClassMethod $method): ?string
    {
        foreach ($method->stmts ?? [] as $stmt) {
            if ($stmt instanceof Stmt\Return_ && $stmt->expr instanceof Node\Scalar\String_) {
                return $stmt->expr->value;
            }
        }

        return null;
    }

    /**
     * @return array<string>
     */
    private function extractReturnedStringArray(Stmt\ClassMethod $method): array
    {
        foreach ($method->stmts ?? [] as $stmt) {
            if (!$stmt instanceof Stmt\Return_ || !$stmt->expr instanceof Expr\Array_) {
                continue;
            }

            $items = [];
            foreach ($stmt->expr->items as $item) {
                if ($item !== null && $item->value instanceof Node\Scalar\String_) {
                    $items[] = $item->value->value;
                }
            }
            return $items;
        }

        return [];
    }

    /**
     * @return array<string>
     */
    private function extractRulesFromMethod(Stmt\ClassMethod $method): array
    {
        foreach ($method->stmts ?? [] as $stmt) {
            if (!$stmt instanceof Stmt\Return_ || !$stmt->expr instanceof Expr\Array_) {
                continue;
            }

            $rules = [];
            foreach ($stmt->expr->items as $item) {
                if ($item !== null && $item->value instanceof Expr\Array_) {
                    $rules[] = $this->normalizeExpressionForReport($item->value);
                }
            }

            return $rules;
        }

        return [];
    }

    private function normalizeExpressionForReport(Expr $expr): string
    {
        if ($expr instanceof Expr\Array_) {
            $parts = [];
            foreach ($expr->items as $item) {
                $value = $item->value;
                if ($value instanceof Node\Scalar\String_) {
                    $parts[] = "'" . $value->value . "'";
                    continue;
                }
                if ($value instanceof Expr\Array_) {
                    $parts[] = '[...]';
                    continue;
                }
                if ($value instanceof Node\Scalar\LNumber) {
                    $parts[] = (string)$value->value;
                }
            }
            return '[' . implode(', ', $parts) . ']';
        }

        return '[]';
    }

    /**
     * @return array<string, string>
     */
    private function extractAssocStringMapFromMethod(Stmt\ClassMethod $method): array
    {
        foreach ($method->stmts ?? [] as $stmt) {
            if (!$stmt instanceof Stmt\Return_ || !$stmt->expr instanceof Expr\Array_) {
                continue;
            }

            $labels = [];
            foreach ($stmt->expr->items as $item) {
                if ($item !== null
                    && $item->key instanceof Node\Scalar\String_
                    && $item->value instanceof Node\Scalar\String_) {
                    $labels[$item->key->value] = $item->value->value;
                }
            }

            return $labels;
        }

        return [];
    }

    private function extractTypeDiscriminatorFromFind(Stmt\ClassMethod $method): ?string
    {
        foreach ($method->stmts ?? [] as $stmt) {
            if (!$stmt instanceof Stmt\Return_ || !$stmt->expr instanceof Expr) {
                continue;
            }

            $whereArgs = $this->findMethodCallArgs($stmt->expr, 'where');
            if ($whereArgs === null || $whereArgs === []) {
                continue;
            }

            $firstArg = $whereArgs[0] ?? null;
            if (!$firstArg instanceof Node\Arg || !$firstArg->value instanceof Expr\Array_) {
                continue;
            }

            foreach ($firstArg->value->items as $item) {
                if ($item !== null
                    && $item->key instanceof Node\Scalar\String_
                    && $item->value instanceof Node\Scalar\String_
                    && $item->key->value === 'type') {
                    return $item->value->value;
                }
            }
        }

        return null;
    }

    /**
     * @return array<int, Node\Arg>|null
     */
    private function findMethodCallArgs(Expr $expr, string $methodName): ?array
    {
        if ($expr instanceof Expr\MethodCall
            && $expr->name instanceof Node\Identifier
            && $expr->name->toString() === $methodName) {
            $args = [];
            foreach ($expr->args as $arg) {
                if ($arg instanceof Node\Arg) {
                    $args[] = $arg;
                }
            }

            return $args;
        }

        if ($expr instanceof Expr\MethodCall) {
            return $this->findMethodCallArgs($expr->var, $methodName);
        }

        return null;
    }

    private function extractTypeDiscriminatorFromBeforeSave(Stmt\ClassMethod $method): ?string
    {
        foreach ($method->stmts ?? [] as $stmt) {
            foreach ($this->findAssignments($stmt) as $assign) {
                if (!$assign->var instanceof Expr\PropertyFetch) {
                    continue;
                }
                if (!$assign->var->name instanceof Node\Identifier) {
                    continue;
                }
                if ($assign->var->name->toString() !== 'type') {
                    continue;
                }
                if ($assign->expr instanceof Node\Scalar\String_) {
                    return $assign->expr->value;
                }
            }
        }

        return null;
    }

    /**
     * @return array<Expr\Assign>
     */
    private function findAssignments(Node $node): array
    {
        $found = [];
        if ($node instanceof Expr\Assign) {
            $found[] = $node;
        }

        foreach ($node->getSubNodeNames() as $name) {
            $sub = $node->$name;
            if ($sub instanceof Node) {
                $found = array_merge($found, $this->findAssignments($sub));
                continue;
            }
            if (!is_array($sub)) {
                continue;
            }
            foreach ($sub as $item) {
                if ($item instanceof Node) {
                    $found = array_merge($found, $this->findAssignments($item));
                }
            }
        }

        return $found;
    }

    /**
     * @param array<string> $relationSqlModifiers
     */
    private function extractRelationFromMethod(string $className, Stmt\ClassMethod $method, array $relationSqlModifiers): ?ModelRelationSchema
    {
        $returnExpr = null;
        foreach ($method->stmts ?? [] as $stmt) {
            if ($stmt instanceof Stmt\Return_ && $stmt->expr instanceof Expr) {
                $returnExpr = $stmt->expr;
                break;
            }
        }

        if (!$returnExpr instanceof Expr) {
            return null;
        }

        $call = $this->findMethodCallNode($returnExpr, ['hasOne', 'hasMany']);
        if (!$call instanceof Expr\MethodCall || !$call->name instanceof Node\Identifier) {
            return null;
        }

        if (count($call->args) < 2) {
            return null;
        }

        $firstArg = $call->args[0] ?? null;
        $secondArg = $call->args[1] ?? null;
        if (!$firstArg instanceof Node\Arg || !$secondArg instanceof Node\Arg) {
            return null;
        }

        $kind = $call->name->toString() === 'hasOne' ? 'many-to-one' : 'one-to-many';
        $target = $this->extractTargetClass($className, $firstArg->value);
        $mapping = $this->extractRelationMapping($secondArg->value);
        $field = lcfirst(substr($method->name->toString(), 3));

        return new ModelRelationSchema(
            name: $field,
            kind: $kind,
            target: $target,
            mapping: $mapping,
            queryModifiers: $this->extractQueryModifiersFromExpression($returnExpr, $relationSqlModifiers),
        );
    }

    /**
     * @param array<int, string> $methodNames
     */
    private function findMethodCallNode(Expr $expr, array $methodNames): ?Expr\MethodCall
    {
        if ($expr instanceof Expr\MethodCall
            && $expr->name instanceof Node\Identifier
            && in_array($expr->name->toString(), $methodNames, true)) {
            return $expr;
        }

        if ($expr instanceof Expr\MethodCall) {
            return $this->findMethodCallNode($expr->var, $methodNames);
        }

        return null;
    }

    private function extractTargetClass(string $className, Expr $expr): string
    {
        if ($expr instanceof Expr\ClassConstFetch
            && $expr->name instanceof Node\Identifier
            && $expr->name->toString() === 'class') {
            if (!$expr->class instanceof Name) {
                return $className;
            }

            $targetRaw = $expr->class->toString();
            if (strtolower($targetRaw) === 'self') {
                return $className;
            }
            return $this->qualifyTarget($className, $targetRaw);
        }

        return $className;
    }

    private function qualifyTarget(string $className, string $target): string
    {
        if (str_contains($target, '\\')) {
            return ltrim($target, '\\');
        }

        $namespace = substr($className, 0, (int)strrpos($className, '\\'));
        return $namespace . '\\' . $target;
    }

    /**
     * @return array<string, string>
     */
    private function extractRelationMapping(Expr $expr): array
    {
        if (!$expr instanceof Expr\Array_) {
            return [];
        }

        $mapping = [];
        foreach ($expr->items as $item) {
            if ($item !== null
                && $item->key instanceof Node\Scalar\String_
                && $item->value instanceof Node\Scalar\String_) {
                $mapping[$item->key->value] = $item->value->value;
            }
        }

        return $mapping;
    }

    /**
     * @param array<string> $relationSqlModifiers
     * @return array<string>
     */
    private function extractQueryModifiersFromExpression(Expr $expr, array $relationSqlModifiers): array
    {
        $found = [];
        $current = $expr;
        while ($current instanceof Expr\MethodCall) {
            if ($current->name instanceof Node\Identifier) {
                $methodName = $current->name->toString();
                if (in_array($methodName, $relationSqlModifiers, true) && !in_array($methodName, $found, true)) {
                    $found[] = $methodName;
                }
            }

            foreach ($current->args as $arg) {
                if (!$arg instanceof Node\Arg || !$arg->value instanceof Expr\Array_) {
                    continue;
                }

                foreach ($arg->value->items as $item) {
                    if (!$item->key instanceof Node\Scalar\String_) {
                        continue;
                    }
                    $key = $item->key->value;
                    if (in_array($key, ['condition', 'order', 'joinType'], true) && !in_array($key, $found, true)) {
                        $found[] = $key;
                    }
                }
            }

            if (!$current->var instanceof Expr) {
                break;
            }

            $current = $current->var;
        }

        return $found;
    }

    /**
     * @param array<string> $fieldNames
     * @return array<object>
     */
    public function buildGeneratedMemberNodes(array $fieldNames, string $generatedMarker = '@generated by doctrinify'): array
    {
        $nodes = [];
        foreach ($fieldNames as $fieldName) {
            $nodes[] = $this->buildGeneratedPropertyNode($fieldName, $generatedMarker);

            $suffix = str_replace(' ', '', ucwords(str_replace('_', ' ', $fieldName)));
            $nodes[] = $this->buildGeneratedGetterNode('get' . $suffix, $fieldName, $generatedMarker);
            $nodes[] = $this->buildGeneratedSetterNode('set' . $suffix, $fieldName, $generatedMarker);
        }

        return $nodes;
    }

    private function buildGeneratedPropertyNode(string $fieldName, string $generatedMarker): Stmt\Property
    {
        $property = new Stmt\Property(
            Stmt\Class_::MODIFIER_PROTECTED,
            [new Stmt\PropertyProperty($fieldName)]
        );
        $property->setDocComment(new Doc("/**\n * {$generatedMarker}\n */"));
        return $property;
    }

    private function buildGeneratedGetterNode(string $methodName, string $fieldName, string $generatedMarker): Stmt\ClassMethod
    {
        $method = new Stmt\ClassMethod($methodName, [
            'flags' => Stmt\Class_::MODIFIER_PUBLIC,
            'stmts' => [
                new Stmt\Return_(new Expr\PropertyFetch(new Expr\Variable('this'), $fieldName)),
            ],
        ]);
        $method->setDocComment(new Doc("/**\n * {$generatedMarker}\n */"));
        return $method;
    }

    private function buildGeneratedSetterNode(string $methodName, string $fieldName, string $generatedMarker): Stmt\ClassMethod
    {
        $method = new Stmt\ClassMethod($methodName, [
            'flags' => Stmt\Class_::MODIFIER_PUBLIC,
            'params' => [new Param(new Expr\Variable('value'))],
            'stmts' => [
                new Stmt\Expression(
                    new Expr\Assign(
                        new Expr\PropertyFetch(new Expr\Variable('this'), $fieldName),
                        new Expr\Variable('value')
                    )
                ),
                new Stmt\Return_(new Expr\Variable('this')),
            ],
            'returnType' => new Name('self'),
        ]);
        $method->setDocComment(new Doc("/**\n * {$generatedMarker}\n */"));
        return $method;
    }

    public function applyMutationPlan(AstClassMutationPlan $plan): void
    {
        $ast = $this->parsePhpFile($plan->targetPath);
        $class = $this->findClassByShortName($ast, $this->shortClassName($plan->className));
        if (!$class instanceof Stmt\Class_) {
            throw new \RuntimeException(sprintf('Class %s not found in %s', $plan->className, $plan->targetPath));
        }

        $class->stmts = $this->withoutGeneratedMembers($class->stmts);
        $existingProps = $this->collectPropertyNames($class->stmts);
        $existingMethods = $this->collectMethodNames($class->stmts);

        foreach ($plan->nodes as $node) {
            if (!$node instanceof Stmt) {
                continue;
            }

            if ($node instanceof Stmt\Property) {
                $name = $node->props[0]->name->toString();
                if (isset($existingProps[strtolower($name)])) {
                    continue;
                }
                $existingProps[strtolower($name)] = true;
                $class->stmts[] = $node;
                continue;
            }

            if ($node instanceof Stmt\ClassMethod) {
                $name = $node->name->toString();
                if (isset($existingMethods[strtolower($name)])) {
                    continue;
                }
                $existingMethods[strtolower($name)] = true;
                $class->stmts[] = $node;
            }
        }

        $this->addHeaderComment($ast, $plan->headerComments);
        $this->writePhpFile($plan->targetPath, $ast);
    }

    /**
     * @param array<int, Stmt> $stmts
     * @return array<int, Stmt>
     */
    private function withoutGeneratedMembers(array $stmts): array
    {
        $clean = [];
        foreach ($stmts as $stmt) {
            if (($stmt instanceof Stmt\Property || $stmt instanceof Stmt\ClassMethod) && $this->isGeneratedNode($stmt)) {
                continue;
            }
            $clean[] = $stmt;
        }

        return $clean;
    }

    private function isGeneratedNode(Node $node): bool
    {
        $doc = $node->getDocComment();
        if ($doc instanceof Doc && str_contains($doc->getText(), self::GENERATED_MARKER_PREFIX)) {
            return true;
        }

        foreach ($node->getComments() as $comment) {
            if (str_contains($comment->getText(), self::GENERATED_MARKER_PREFIX)) {
                return true;
            }
        }

        return false;
    }

    /**
     * @param array<int, Stmt> $stmts
     * @return array<string, bool>
     */
    private function collectPropertyNames(array $stmts): array
    {
        $names = [];
        foreach ($stmts as $stmt) {
            if (!$stmt instanceof Stmt\Property) {
                continue;
            }

            foreach ($stmt->props as $prop) {
                $names[strtolower($prop->name->toString())] = true;
            }
        }

        return $names;
    }

    /**
     * @param array<int, Stmt> $stmts
     * @return array<string, bool>
     */
    private function collectMethodNames(array $stmts): array
    {
        $names = [];
        foreach ($stmts as $stmt) {
            if ($stmt instanceof Stmt\ClassMethod) {
                $names[strtolower($stmt->name->toString())] = true;
            }
        }

        return $names;
    }

    /**
     * @param array<int, Stmt> $ast
     * @param array<string> $headerComments
     */
    private function addHeaderComment(array $ast, array $headerComments): void
    {
        if ($headerComments === []) {
            return;
        }

        $commentText = '// ' . implode(' | ', $headerComments);
        $first = $ast[0] ?? null;
        if ($first instanceof Stmt\Declare_) {
            $first->setAttribute('comments', [new Comment($commentText)]);
            return;
        }

        if ($first instanceof Stmt) {
            $first->setAttribute('comments', [new Comment($commentText)]);
        }
    }

    /**
     * @param array<int, Stmt> $ast
     */
    private function writePhpFile(string $path, array $ast): void
    {
        $printer = new Standard();
        $rendered = $printer->prettyPrintFile($ast) . "\n";
        if (file_put_contents($path, $rendered) === false) {
            throw new \RuntimeException(sprintf('Failed to write PHP file: %s', $path));
        }
    }

    public function cleanupGeneratedMembers(string $filePath, string $className): bool
    {
        if (!is_file($filePath)) {
            return false;
        }

        $ast = $this->parsePhpFile($filePath);
        $class = $this->findClassByShortName($ast, $this->shortClassName($className));
        if (!$class instanceof Stmt\Class_) {
            return false;
        }

        $class->stmts = $this->withoutGeneratedMembers($class->stmts);
        $this->writePhpFile($filePath, $ast);

        return true;
    }
}
