-- Oracle mock schema for legacy-style introspection.
-- Includes: PK (single/composite), FK (simple/composite), sequences, self-reference,
-- and a simple many-to-many join table pattern.

CREATE TABLE CUSTOMER (
    ID NUMBER(10) NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    EMAIL VARCHAR2(255 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID),
    CONSTRAINT UQ_CUSTOMER_EMAIL UNIQUE (EMAIL)
);

CREATE TABLE PRODUCT (
    ID NUMBER(10) NOT NULL,
    SKU VARCHAR2(50 CHAR) NOT NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    STOCK NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT UQ_PRODUCT_SKU UNIQUE (SKU)
);

CREATE TABLE CATEGORY (
    ID NUMBER(10) NOT NULL,
    PARENT_ID NUMBER(10) NULL,
    NAME VARCHAR2(255 CHAR) NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID),
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY (ID)
);

CREATE TABLE PRODUCT_CATEGORY (
    PRODUCT_ID NUMBER(10) NOT NULL,
    CATEGORY_ID NUMBER(10) NOT NULL,
    ASSIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_PRODUCT_CATEGORY PRIMARY KEY (PRODUCT_ID, CATEGORY_ID),
    CONSTRAINT FK_PC_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    CONSTRAINT FK_PC_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);

CREATE TABLE "ORDER" (
    ORDER_ID NUMBER(10) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    STATUS VARCHAR2(20 CHAR) DEFAULT 'new',
    CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_ID, CUSTOMER_ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID)
);

CREATE TABLE ORDER_ITEM (
    ID NUMBER(10) NOT NULL,
    ORDER_ID NUMBER(10) NOT NULL,
    CUSTOMER_ID NUMBER(10) NOT NULL,
    PRODUCT_ID NUMBER(10) NOT NULL,
    QUANTITY NUMBER(10) NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_ID, CUSTOMER_ID)
        REFERENCES "ORDER" (ORDER_ID, CUSTOMER_ID),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE "USER" (
    ID NUMBER(10) NOT NULL,
    USERNAME VARCHAR2(50 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(255 CHAR) NOT NULL,
    TYPE VARCHAR2(20 CHAR) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UQ_USER_USERNAME UNIQUE (USERNAME)
);

CREATE SEQUENCE SEQ_CUSTOMER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCT START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORY START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ORDER_ITEM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USER START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
