<?php

declare(strict_types=1);

namespace Doctrinify\Tools\Persist;

use Doctrinify\Tools\AST\AstClassMutationPlan;
use Doctrinify\Tools\AST\AstFacade;
use Doctrinify\Tools\Schemas\Pipeline\GenerationResultSchema;
use Doctrinify\Tools\Schemas\Pipeline\PhpPersistInstructionSchema;
use Doctrinify\Tools\Schemas\Pipeline\PersistResultSchema;
use Doctrinify\Tools\Schemas\ProjectProfileInterface;

final class ArtifactPersister
{
    private const GENERATED_MARKER = '@generated by doctrinify';

    public function __construct(private readonly ?AstFacade $astFacade = null)
    {
    }

    public function persist(GenerationResultSchema $result, string $xmlOutputPath, string $phpOutputPath, ProjectProfileInterface $profile): PersistResultSchema
    {
        $this->ensureDirectory($xmlOutputPath);
        $this->ensureDirectory($phpOutputPath);

        $xmlFiles = [];
        $phpFiles = [];
        foreach ($result->artifacts as $artifact) {
            if ($artifact->xml !== null && $artifact->xmlFilename !== null) {
                $xmlFile = $xmlOutputPath . '/' . $artifact->xmlFilename;
                if ($this->shouldWriteFile($xmlFile, $profile)) {
                    file_put_contents($xmlFile, $artifact->xml);
                }
                $xmlFiles[] = $xmlFile;
            }

            if ($artifact->phpInstruction !== null) {
                $phpFiles[] = $this->persistPhpInstruction($artifact->phpInstruction, $profile);
                continue;
            }

            if ($artifact->php !== null && $artifact->phpFilename !== null) {
                $phpFile = $phpOutputPath . '/' . $artifact->phpFilename;
                if ($this->shouldWriteFile($phpFile, $profile)) {
                    file_put_contents($phpFile, $artifact->php);
                }
                $phpFiles[] = $phpFile;
            }
        }

        $reportPath = $xmlOutputPath . '/mismatch-report.txt';
        file_put_contents($reportPath, $result->report);

        return new PersistResultSchema($xmlFiles, $phpFiles, $reportPath);
    }

    public function clean(string $xmlOutputPath, string $phpOutputPath): void
    {
        $this->removeDirectoryContents($xmlOutputPath);
        if ($phpOutputPath !== '') {
            $this->removeDirectoryContents($phpOutputPath);
        }
    }

    /**
     * @param array<string, string> $classFiles
     */
    public function cleanGeneratedAstMembers(array $classFiles): void
    {
        $ast = $this->astFacade ?? new AstFacade();
        foreach ($classFiles as $className => $filePath) {
            $ast->cleanupGeneratedMembers($filePath, (string) $className);
        }
    }

    private function shouldWriteFile(string $filePath, ProjectProfileInterface $profile): bool
    {
        $strategy = $profile->getRegenerationStrategy();
        if ($strategy === 'overwrite_all' || !is_file($filePath)) {
            return true;
        }

        if ($strategy === 'preserve_custom') {
            $existing = file_get_contents($filePath);
            if ($existing === false) {
                return true;
            }

            return str_contains($existing, self::GENERATED_MARKER);
        }

        return true;
    }

    private function ensureDirectory(string $path): void
    {
        if ($path === '') {
            return;
        }

        if (!is_dir($path) && !mkdir($path, 0777, true) && !is_dir($path)) {
            throw new \RuntimeException(sprintf('Failed to create directory: %s', $path));
        }
    }

    private function removeDirectoryContents(string $path): void
    {
        if (!is_dir($path)) {
            return;
        }

        $items = scandir($path);
        if ($items === false) {
            return;
        }

        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }

            $full = $path . '/' . $item;
            if (is_dir($full)) {
                $this->removeDirectoryContents($full);
                rmdir($full);
                continue;
            }

            unlink($full);
        }
    }

    private function persistPhpInstruction(PhpPersistInstructionSchema $instruction, ProjectProfileInterface $profile): string
    {
        $targetPath = $instruction->targetPath;
        if ($targetPath === '') {
            throw new \RuntimeException('PHP persist instruction targetPath is empty');
        }

        if ($instruction->mode === 'full_content') {
            if ($instruction->content === null) {
                throw new \RuntimeException('PHP full_content instruction has empty content');
            }

            $this->ensureDirectory(dirname($targetPath));
            if ($this->shouldWriteFile($targetPath, $profile)) {
                file_put_contents($targetPath, $instruction->content);
            }

            return $targetPath;
        }

        if ($instruction->mode !== 'ast_nodes') {
            throw new \RuntimeException(sprintf('Unsupported PHP persist instruction mode: %s', $instruction->mode));
        }

        $ast = $this->astFacade ?? new AstFacade();
        $plan = new AstClassMutationPlan(
            targetPath: $instruction->targetPath,
            className: $instruction->className,
            nodes: $instruction->astNodes,
            headerComments: $instruction->headerComments,
        );

        $ast->applyMutationPlan($plan);
        return $targetPath;
    }
}
