<?php

declare(strict_types=1);

namespace Tests\Unit;

use Codeception\Test\Unit;
use Doctrinify\Tools\AST\AstClassMutationPlan;
use Doctrinify\Tools\AST\AstFacade;

final class AstFacadeTest extends Unit
{
    private string $projectRoot;
    private AstFacade $facade;

    protected function _before(): void
    {
        $this->projectRoot = dirname(__DIR__, 2);
        $this->facade = new AstFacade();
    }

    public function testExtractFirstClassInfoUsesAst(): void
    {
        $info = $this->facade->extractFirstClassInfo($this->projectRoot . '/tests/_data/mock/models/Product.php');
        $this->assertNotNull($info);
        assert($info !== null);
        $this->assertSame('app\\models\\Product', $info['fqn']);
        $this->assertContains('tableName', $info['methodNames']);
        $this->assertContains('getCategoriesWithSql', $info['methodNames']);
    }

    public function testIntrospectModelParsesSqlRelationModifiersViaAst(): void
    {
        $meta = $this->facade->introspectModel(
            'app\\models\\Product',
            $this->projectRoot . '/tests/_data/mock/models/Product.php',
            ['where', 'andWhere', 'orderBy', 'addOrderBy', 'joinWith', 'condition', 'order', 'joinType']
        );

        $this->assertNotNull($meta);
        assert($meta !== null);

        $target = null;
        foreach ($meta->relations as $relation) {
            if ($relation->name === 'categoriesWithSql') {
                $target = $relation;
                break;
            }
        }

        $this->assertNotNull($target);
        assert($target !== null);
        $this->assertContains('where', $target->queryModifiers);
        $this->assertContains('joinType', $target->queryModifiers);
    }

    public function testApplyAndCleanupMutationPlan(): void
    {
        $runtimeDir = $this->projectRoot . '/tests/_output/ast_facade';
        if (!is_dir($runtimeDir)) {
            mkdir($runtimeDir, 0777, true);
        }

        $target = $runtimeDir . '/Product.php';
        copy($this->projectRoot . '/tests/_data/mock/models/Product.php', $target);

        $plan = new AstClassMutationPlan(
            targetPath: $target,
            className: 'app\\models\\Product',
            nodes: $this->facade->buildGeneratedMemberNodes(['id', 'name']),
            headerComments: ['@generated by doctrinify'],
        );

        $this->facade->applyMutationPlan($plan);
        $content = (string) file_get_contents($target);
        $this->assertStringContainsString('function getName', $content);
        $this->assertStringContainsString('@generated by doctrinify', $content);

        $this->facade->cleanupGeneratedMembers($target, 'app\\models\\Product');
        $cleaned = (string) file_get_contents($target);
        $this->assertStringNotContainsString('function getName', $cleaned);
    }
}
