<?php

declare(strict_types=1);

namespace Tests\Unit;

use Codeception\Test\Unit;
use Doctrinify\Service\OrmGeneratorService;

final class OrmGeneratorServiceTest extends Unit
{
    private OrmGeneratorService $service;
    private string $projectRoot;
    private string $configPath;

    protected function _before(): void
    {
        $this->projectRoot = dirname(__DIR__, 2);
        $this->configPath = $this->projectRoot . '/tests/_data/mock/config.yaml';
        $this->service = new OrmGeneratorService($this->projectRoot);

        $this->service->clean($this->configPath);
        $this->service->generate($this->configPath);
    }

    public function testGeneratesAllExpectedFiles(): void
    {
        $expectedXml = glob($this->projectRoot . '/tests/_data/expected/doctrine/*.orm.xml') ?: [];
        $expectedPhp = glob($this->projectRoot . '/tests/_data/expected/classes/*.php') ?: [];

        $actualXml = glob($this->projectRoot . '/tests/_output/generated/doctrine/*.orm.xml') ?: [];
        $actualPhp = glob($this->projectRoot . '/tests/_output/generated/classes/*.php') ?: [];

        sort($expectedXml);
        sort($expectedPhp);
        sort($actualXml);
        sort($actualPhp);

        $this->assertCount(count($expectedXml), $actualXml, 'Unexpected Doctrine XML file count');
        $this->assertCount(count($expectedPhp), $actualPhp, 'Unexpected generated PHP file count');
    }

    /**
     * @dataProvider xmlFixtureProvider
     */
    public function testDoctrineXmlMatchesExpected(string $fileName): void
    {
        $expected = $this->canonicalizeXmlFile($this->projectRoot . '/tests/_data/expected/doctrine/' . $fileName);
        $actual = $this->canonicalizeXmlFile($this->projectRoot . '/tests/_output/generated/doctrine/' . $fileName);

        $this->assertSame($expected, $actual, 'XML mismatch for ' . $fileName);
    }

    /**
     * @dataProvider generatedAccessorProvider
     */
    public function testGeneratedAccessorContainsExpectedMethods(string $classFile, string $getter, string $setter): void
    {
        $generatedFile = $this->projectRoot . '/tests/_output/generated/classes/' . $classFile;
        $contents = (string) file_get_contents($generatedFile);

        $this->assertStringContainsString('function ' . $getter . '()', $contents);
        $this->assertStringContainsString('function ' . $setter . '($value): self', $contents);
    }

    /**
     * @dataProvider xmlXpathProvider
     */
    public function testXmlContainsExpectedXpath(string $fileName, string $xpath, int $expectedCount): void
    {
        $xmlPath = $this->projectRoot . '/tests/_output/generated/doctrine/' . $fileName;
        $xml = simplexml_load_file($xmlPath);

        $this->assertNotFalse($xml, 'Unable to parse XML ' . $fileName);
        assert($xml instanceof \SimpleXMLElement);

        $result = $xml->xpath($xpath);
        $count = is_array($result) ? count($result) : 0;
        $this->assertSame($expectedCount, $count, sprintf('XPath check failed for %s: %s', $fileName, $xpath));
    }

    public function testCleanRemovesGeneratedArtifacts(): void
    {
        $this->service->clean($this->configPath);

        $xmlFiles = glob($this->projectRoot . '/tests/_output/generated/doctrine/*.orm.xml') ?: [];
        $phpFiles = glob($this->projectRoot . '/tests/_output/generated/classes/*.php') ?: [];

        $this->assertCount(0, $xmlFiles);
        $this->assertCount(0, $phpFiles);
    }

    public function testRepeatedGenerateIsIdempotentForArtifacts(): void
    {
        $before = $this->snapshotGeneratedArtifacts();
        $this->service->generate($this->configPath);
        $after = $this->snapshotGeneratedArtifacts();

        $this->assertSame($before, $after, 'Artifact content changed after second generate');
    }

    public function testGeneratedArtifactsContainCodegenMarkers(): void
    {
        $xml = (string) file_get_contents($this->projectRoot . '/tests/_output/generated/doctrine/Product.orm.xml');
        $php = (string) file_get_contents($this->projectRoot . '/tests/_output/generated/classes/Product.php');

        $this->assertStringContainsString('@generated by doctrinify', $xml);
        $this->assertStringContainsString('strategy=overwrite_all', $xml);
        $this->assertStringContainsString('@generated by doctrinify', $php);
        $this->assertStringContainsString('strategy=overwrite_all', $php);
    }

    public function testMismatchReportContainsStrategyAndRejectedSqlRelations(): void
    {
        $reportPath = $this->projectRoot . '/tests/_output/generated/doctrine/mismatch-report.txt';
        $report = (string) file_get_contents($reportPath);

        $this->assertStringContainsString('[info] regeneration strategy: overwrite_all', $report);
        $this->assertStringContainsString('relation `categoriesWithSql` rejected', $report);
        $this->assertStringContainsString('relation `itemsWithCondition` rejected', $report);
        $this->assertStringContainsString('contains SQL query modifiers', $report);
        $this->assertStringContainsString('condition', $report);
        $this->assertStringContainsString('order', $report);
        $this->assertStringContainsString('joinType', $report);
    }

    public function testGenerateWithoutClassListFallsBackToAutoscan(): void
    {
        $autoscanConfig = $this->projectRoot . '/tests/_output/autoscan-config.yaml';
        $config = (string) file_get_contents($this->configPath);
        $this->assertNotFalse($config);
        $updated = $config . "\nclasslist_path: 'tests/_output/missing-classlist.txt'\n";
        file_put_contents($autoscanConfig, $updated);

        $this->service->clean($autoscanConfig);
        $result = $this->service->generate($autoscanConfig);

        $this->assertCount(9, $result['xml_files']);
        $this->assertNotEmpty($result['warnings'] ?? []);
        $warnings = is_array($result['warnings'] ?? null) ? $result['warnings'] : [];
        $this->assertStringContainsString('fallback to models_path autoscan', (string) ($warnings[0] ?? ''));
    }

    public function testRepeatedGenerateIsIdempotentWithoutClassList(): void
    {
        $autoscanConfig = $this->projectRoot . '/tests/_output/autoscan-config-idempotent.yaml';
        $config = (string) file_get_contents($this->configPath);
        $this->assertNotFalse($config);
        $updated = $config . "\nclasslist_path: 'tests/_output/missing-classlist-for-idempotent.txt'\n";
        file_put_contents($autoscanConfig, $updated);

        $this->service->clean($autoscanConfig);
        $this->service->generate($autoscanConfig);
        $before = $this->snapshotGeneratedArtifacts();

        $this->service->generate($autoscanConfig);
        $after = $this->snapshotGeneratedArtifacts();

        $this->assertSame($before, $after, 'Artifact content changed after second autoscan-based generate');
    }

    public function testPreserveCustomStrategyWorksWithoutClassList(): void
    {
        $targetFile = $this->projectRoot . '/tests/_output/generated/classes/Product.php';
        file_put_contents($targetFile, "<?php\n// custom file without generated marker\n");

        $config = (string) file_get_contents($this->configPath);
        $this->assertNotFalse($config);
        $updated = str_replace('strategy: "overwrite_all"', 'strategy: "preserve_custom"', $config);
        $this->assertNotFalse($updated);
        $updated .= "\nclasslist_path: 'tests/_output/missing-classlist-for-preserve.txt'\n";

        $preserveAutoscanConfig = $this->projectRoot . '/tests/_output/preserve-autoscan-config.yaml';
        file_put_contents($preserveAutoscanConfig, $updated);

        $this->service->generate($preserveAutoscanConfig);
        $actual = (string) file_get_contents($targetFile);
        $this->assertStringContainsString('custom file without generated marker', $actual);
    }

    public function testPreserveCustomStrategyKeepsUnmanagedPhpFile(): void
    {
        $targetFile = $this->projectRoot . '/tests/_output/generated/classes/Product.php';
        file_put_contents($targetFile, "<?php\n// custom file without generated marker\n");

        $preserveConfig = $this->projectRoot . '/tests/_output/preserve-config.yaml';
        $config = (string) file_get_contents($this->configPath);
        $this->assertNotFalse($config);
        $updated = str_replace('strategy: "overwrite_all"', 'strategy: "preserve_custom"', $config);
        $this->assertNotFalse($updated);
        file_put_contents($preserveConfig, $updated);
        copy($this->projectRoot . '/tests/_data/mock/classlist.txt', $this->projectRoot . '/tests/_output/classlist.txt');

        $this->service->generate($preserveConfig);
        $actual = (string) file_get_contents($targetFile);
        $this->assertStringContainsString('custom file without generated marker', $actual);
    }

    public function testCustomProjectProfileAffectsXmlFilenameAndPhpNamespace(): void
    {
        $targetOutputDoctrine = $this->projectRoot . '/tests/_output/generated/doctrine_custom';
        $targetOutputPhp = $this->projectRoot . '/tests/_output/generated/classes_custom';
        @mkdir($targetOutputDoctrine, 0777, true);
        @mkdir($targetOutputPhp, 0777, true);

        $customConfigPath = $this->projectRoot . '/tests/_output/custom-profile-config.yaml';
        $config = <<<YAML
models_path: 'tests/_data/mock/models'
base_classes:
  - 'app\\\\models\\\\BaseModel'
doctrine_xml_path: 'tests/_output/generated/doctrine_custom'
generated_php_path: 'tests/_output/generated/classes_custom'
schema_path: 'tests/_data/mock/database/schema.sql'
flags:
  generate_doctrine_xml: true
  generate_php_accessors: true
  use_ast_parsing: true
project_profile:
  doctrine_xml:
    root_attributes:
      xmlns: "http://doctrine-project.org/schemas/orm/doctrine-mapping"
      xmlns:xsi: "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation: "http://doctrine-project.org/schemas/orm/doctrine-mapping https://doctrine-project.org/schemas/orm/doctrine-mapping.xsd"
    filename_pattern: "map_{class}.xml"
  generated_php:
    namespace: "custom\\\\generated"
  regeneration:
    strategy: "overwrite_all"
    add_generated_marker: true
    embed_diagnostics: false
YAML;
        file_put_contents($customConfigPath, $config);
        copy($this->projectRoot . '/tests/_data/mock/classlist.txt', $this->projectRoot . '/tests/_output/classlist.txt');

        $this->service->generate($customConfigPath);

        $xmlFile = $this->projectRoot . '/tests/_output/generated/doctrine_custom/map_Product.xml';
        $phpFile = $this->projectRoot . '/tests/_output/generated/classes_custom/Product.php';
        $xml = (string) file_get_contents($xmlFile);
        $php = (string) file_get_contents($phpFile);

        $this->assertFileExists($xmlFile);
        $this->assertStringContainsString('xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"', $xml);
        $this->assertStringContainsString('xsi:schemaLocation=', $xml);
        $this->assertStringContainsString('namespace custom\\generated;', $php);
    }

    /**
     * @return array<string, array{0:string}>
     */
    public function xmlFixtureProvider(): array
    {
        return [
            'admin' => ['Admin.orm.xml'],
            'category' => ['Category.orm.xml'],
            'customer' => ['Customer.orm.xml'],
            'moderator' => ['Moderator.orm.xml'],
            'order' => ['Order.orm.xml'],
            'orderItem' => ['OrderItem.orm.xml'],
            'product' => ['Product.orm.xml'],
            'productCategory' => ['ProductCategory.orm.xml'],
            'user' => ['User.orm.xml'],
        ];
    }

    /**
     * @return array<string, array{0:string,1:string,2:string}>
     */
    public function generatedAccessorProvider(): array
    {
        return [
            'category accessors' => ['Category.php', 'getParentId', 'setParentId'],
            'user accessors' => ['User.php', 'getUsername', 'setUsername'],
            'productCategory accessors' => ['ProductCategory.php', 'getCategoryId', 'setCategoryId'],
            'orderItem accessors' => ['OrderItem.php', 'getCustomerId', 'setCustomerId'],
        ];
    }

    /**
     * @return array<string, array{0:string,1:string,2:int}>
     */
    public function xmlXpathProvider(): array
    {
        return [
            'category parent relation' => ['Category.orm.xml', '//*[local-name()="many-to-one" and @field="parent" and @target-entity="app\\models\\Category"]', 1],
            'category children relation' => ['Category.orm.xml', '//*[local-name()="one-to-many" and @field="children" and @target-entity="app\\models\\Category"]', 1],
            'user discriminator column' => ['User.orm.xml', '//*[local-name()="discriminator-column" and @name="type"]', 1],
            'user discriminator map entries' => ['User.orm.xml', '//*[local-name()="discriminator-mapping"]', 3],
            'productCategory composite id' => ['ProductCategory.orm.xml', '//*[local-name()="id"]', 2],
            'product sql relation rejected' => ['Product.orm.xml', '//*[local-name()="one-to-many" and @field="categoriesWithSql"]', 0],
            'order sql relation rejected' => ['Order.orm.xml', '//*[local-name()="one-to-many" and @field="itemsWithCondition"]', 0],
        ];
    }

    private function canonicalizeXmlFile(string $path): string
    {
        $dom = new \DOMDocument();
        $dom->preserveWhiteSpace = false;
        $loaded = $dom->load($path);
        $this->assertTrue($loaded, 'Invalid XML at ' . $path);

        $canonical = $dom->C14N();
        $this->assertNotFalse($canonical, 'Unable to canonicalize XML at ' . $path);

        return (string) $canonical;
    }

    /**
     * @return array<string, string>
     */
    private function snapshotGeneratedArtifacts(): array
    {
        $snapshot = [];
        $files = array_merge(
            glob($this->projectRoot . '/tests/_output/generated/doctrine/*.orm.xml') ?: [],
            glob($this->projectRoot . '/tests/_output/generated/classes/*.php') ?: []
        );

        sort($files);
        foreach ($files as $file) {
            $contents = file_get_contents($file);
            $this->assertNotFalse($contents, 'Failed to read generated file: ' . $file);
            $snapshot[basename($file)] = hash('sha256', (string) $contents);
        }

        return $snapshot;
    }
}
