<?php

declare(strict_types=1);

namespace Tests\Unit;

use Codeception\Test\Unit;
use App\Service\OrmGeneratorService;

final class OrmGeneratorServiceTest extends Unit
{
    private OrmGeneratorService $service;
    private string $projectRoot;
    private string $configPath;
    private string $runtimeModelsDir;

    protected function _before(): void
    {
        $this->projectRoot = dirname(__DIR__, 2);
        $this->configPath = $this->projectRoot . '/tests/_data/mock/config.yaml';
        $this->runtimeModelsDir = $this->projectRoot . '/tests/_output/sandbox/models';
        $this->service = new OrmGeneratorService($this->projectRoot);

        $this->resetDir($this->runtimeModelsDir);
        $this->copyDir($this->projectRoot . '/tests/_data/mock/models', $this->runtimeModelsDir);

        $this->service->clean($this->configPath);
        $this->service->generate($this->configPath);
    }

    public function testGeneratesAllExpectedXmlAndUpdatesModelsInPlace(): void
    {
        $xmlFiles = glob($this->projectRoot . '/tests/_output/generated/doctrine/*.orm.xml') ?: [];
        sort($xmlFiles);
        $this->assertCount(9, $xmlFiles);

        $product = (string) file_get_contents($this->runtimeModelsDir . '/Product.php');
        $this->assertStringContainsString('function getName', $product);
        $this->assertStringContainsString('function setName', $product);
        $this->assertStringContainsString('@generated by doctrinify', $product);
    }

    /**
     * @dataProvider xmlFixtureProvider
     */
    public function testDoctrineXmlMatchesExpected(string $fileName): void
    {
        $expected = $this->canonicalizeXmlFile($this->projectRoot . '/tests/_data/expected/doctrine/' . $fileName);
        $actual = $this->canonicalizeXmlFile($this->projectRoot . '/tests/_output/generated/doctrine/' . $fileName);
        $this->assertSame($expected, $actual, 'XML mismatch for ' . $fileName);
    }

    public function testCleanRemovesXmlAndAstGeneratedMembers(): void
    {
        $this->service->clean($this->configPath);

        $xmlFiles = glob($this->projectRoot . '/tests/_output/generated/doctrine/*.orm.xml') ?: [];
        $this->assertCount(0, $xmlFiles);

        $product = (string) file_get_contents($this->runtimeModelsDir . '/Product.php');
        $this->assertStringNotContainsString('function getName', $product);
    }

    public function testRepeatedGenerateIsIdempotent(): void
    {
        $before = $this->snapshotGeneratedArtifacts();
        $this->service->generate($this->configPath);
        $after = $this->snapshotGeneratedArtifacts();
        $this->assertSame($before, $after);
    }

    public function testMismatchReportContainsRelationDiagnostics(): void
    {
        $reportPath = $this->projectRoot . '/tests/_output/generated/doctrine/mismatch-report.txt';
        $report = (string) file_get_contents($reportPath);
        $this->assertStringContainsString('relation `categoriesWithSql` has SQL modifiers', $report);
        $this->assertStringContainsString('relation `itemsWithCondition` has SQL modifiers', $report);
    }

    public function testGenerateWithoutClassListFallsBackToAutoscan(): void
    {
        $autoscanConfig = $this->projectRoot . '/tests/_output/autoscan-config.yaml';
        $config = (string) file_get_contents($this->configPath);
        $this->assertNotFalse($config);
        file_put_contents($autoscanConfig, $config . "\nclasslist_path: 'tests/_output/missing-classlist.txt'\n");

        $this->service->clean($autoscanConfig);
        $result = $this->service->generate($autoscanConfig);

        $this->assertCount(9, $result['xml_files']);
        $warnings = is_array($result['warnings'] ?? null) ? $result['warnings'] : [];
        $this->assertNotEmpty($warnings);
        $this->assertStringContainsString('fallback to models_path autoscan', (string) ($warnings[0] ?? ''));
    }

    public function testCustomProfileCanChangeXmlFilenamePattern(): void
    {
        $targetOutputDoctrine = $this->projectRoot . '/tests/_output/generated/doctrine_custom';
        @mkdir($targetOutputDoctrine, 0777, true);

        $customModels = $this->projectRoot . '/tests/_output/sandbox/models_custom';
        $this->resetDir($customModels);
        $this->copyDir($this->projectRoot . '/tests/_data/mock/models', $customModels);

        $customConfigPath = $this->projectRoot . '/tests/_output/custom-profile-config.yaml';
        $config = <<<YAML
models_path: 'tests/_output/sandbox/models_custom'
base_classes:
  - 'app\\\\models\\\\BaseModel'
doctrine_xml_path: 'tests/_output/generated/doctrine_custom'
schema_path: 'tests/_data/oracle/schema.sql'
flags:
  generate_doctrine_xml: true
  generate_php_accessors: true
tooling:
  doctrine_xml:
    root_attributes:
      xmlns: "http://doctrine-project.org/schemas/orm/doctrine-mapping"
      xmlns:xsi: "http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation: "http://doctrine-project.org/schemas/orm/doctrine-mapping https://doctrine-project.org/schemas/orm/doctrine-mapping.xsd"
    filename_pattern: "map_{class}.xml"
  regeneration:
    add_generated_marker: true
    embed_diagnostics: false
YAML;
        file_put_contents($customConfigPath, $config);
        copy($this->projectRoot . '/tests/_data/mock/classlist.txt', $this->projectRoot . '/tests/_output/classlist.txt');

        $this->service->generate($customConfigPath);

        $xmlFile = $targetOutputDoctrine . '/map_Product.xml';
        $this->assertFileExists($xmlFile);
        $product = (string) file_get_contents($customModels . '/Product.php');
        $this->assertStringContainsString('function getName', $product);
    }

    public function testHierarchyWithAbstractOrderClassesGeneratesOnlyConcreteXml(): void
    {
        $modelsDir = $this->projectRoot . '/tests/_output/hierarchy/models';
        $xmlDir = $this->projectRoot . '/tests/_output/hierarchy/doctrine';
        $schemaPath = $this->projectRoot . '/tests/_output/hierarchy/schema.sql';
        $configPath = $this->projectRoot . '/tests/_output/hierarchy/config.yaml';
        $classlistPath = $this->projectRoot . '/tests/_output/hierarchy/classlist.txt';

        $this->resetDir($modelsDir);
        @mkdir($xmlDir, 0777, true);
        file_put_contents($schemaPath, "CREATE TABLE \"ORDER\" (\n  \"ORDER_ID\" NUMBER(11) NOT NULL,\n  \"STATUS\" VARCHAR2(20),\n  CONSTRAINT \"PK_ORDER\" PRIMARY KEY (\"ORDER_ID\")\n);\n");

        file_put_contents($modelsDir . '/BaseModel.php', "<?php\nnamespace app\\models;\nabstract class BaseModel {}\n");
        file_put_contents($modelsDir . '/AbstractOrder.php', "<?php\nnamespace app\\models;\nabstract class AbstractOrder extends BaseModel { public static function tableName(){ return 'order'; } }\n");
        file_put_contents($modelsDir . '/AbstractRegionalOrder.php', "<?php\nnamespace app\\models;\nabstract class AbstractRegionalOrder extends AbstractOrder {}\n");
        file_put_contents($modelsDir . '/RetailOrder.php', "<?php\nnamespace app\\models;\nclass RetailOrder extends AbstractRegionalOrder {}\n");
        file_put_contents($modelsDir . '/WholesaleOrder.php', "<?php\nnamespace app\\models;\nclass WholesaleOrder extends AbstractRegionalOrder {}\n");

        file_put_contents($classlistPath, "app\\models\\RetailOrder\napp\\models\\WholesaleOrder\n");

        $config = <<<YAML
models_path: 'tests/_output/hierarchy/models'
classlist_path: 'tests/_output/hierarchy/classlist.txt'
base_classes:
  - 'app\\\\models\\\\BaseModel'
doctrine_xml_path: 'tests/_output/hierarchy/doctrine'
schema_path: 'tests/_output/hierarchy/schema.sql'
flags:
  generate_doctrine_xml: true
  generate_php_accessors: true
tooling:
  doctrine_xml:
    filename_pattern: '{class}.orm.xml'
  regeneration:
    add_generated_marker: true
    embed_diagnostics: false
YAML;
        file_put_contents($configPath, $config);

        $this->service->clean($configPath);
        $this->service->generate($configPath);

        $this->assertFileExists($xmlDir . '/RetailOrder.orm.xml');
        $this->assertFileExists($xmlDir . '/WholesaleOrder.orm.xml');
        $this->assertFileDoesNotExist($xmlDir . '/AbstractOrder.orm.xml');
        $this->assertFileDoesNotExist($xmlDir . '/AbstractRegionalOrder.orm.xml');
    }

    /**
     * @return array<string, array{0:string}>
     */
    public function xmlFixtureProvider(): array
    {
        return [
            'admin' => ['Admin.orm.xml'],
            'category' => ['Category.orm.xml'],
            'customer' => ['Customer.orm.xml'],
            'moderator' => ['Moderator.orm.xml'],
            'order' => ['Order.orm.xml'],
            'orderItem' => ['OrderItem.orm.xml'],
            'product' => ['Product.orm.xml'],
            'productCategory' => ['ProductCategory.orm.xml'],
            'user' => ['User.orm.xml'],
        ];
    }

    private function canonicalizeXmlFile(string $path): string
    {
        $dom = new \DOMDocument();
        $dom->preserveWhiteSpace = false;
        $loaded = $dom->load($path);
        $this->assertTrue($loaded, 'Invalid XML at ' . $path);

        $canonical = $dom->C14N();
        $this->assertNotFalse($canonical, 'Unable to canonicalize XML at ' . $path);

        return (string) $canonical;
    }

    /**
     * @return array<string, string>
     */
    private function snapshotGeneratedArtifacts(): array
    {
        $snapshot = [];
        $files = array_merge(
            glob($this->projectRoot . '/tests/_output/generated/doctrine/*.orm.xml') ?: [],
            glob($this->runtimeModelsDir . '/*.php') ?: []
        );

        sort($files);
        foreach ($files as $file) {
            $contents = file_get_contents($file);
            $this->assertNotFalse($contents, 'Failed to read generated file: ' . $file);
            $snapshot[$file] = hash('sha256', (string) $contents);
        }

        return $snapshot;
    }

    private function resetDir(string $path): void
    {
        if (is_dir($path)) {
            $items = scandir($path);
            if ($items !== false) {
                foreach ($items as $item) {
                    if ($item === '.' || $item === '..') {
                        continue;
                    }
                    $full = $path . '/' . $item;
                    if (is_file($full)) {
                        unlink($full);
                    }
                }
            }
            return;
        }

        mkdir($path, 0777, true);
    }

    private function copyDir(string $from, string $to): void
    {
        if (!is_dir($to) && !mkdir($to, 0777, true) && !is_dir($to)) {
            throw new \RuntimeException('Cannot create directory: ' . $to);
        }

        $items = scandir($from);
        if ($items === false) {
            return;
        }

        foreach ($items as $item) {
            if ($item === '.' || $item === '..') {
                continue;
            }
            $src = $from . '/' . $item;
            $dst = $to . '/' . $item;
            if (is_file($src)) {
                copy($src, $dst);
            }
        }
    }
}
